apiVersion: v1
kind: ServiceAccount
metadata:
  name: encrypt
---
apiVersion: v1
kind: Service
metadata:
  name: encrypt
  labels:
    app: encrypt
    service: encrypt
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: encrypt
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: encrypt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: encrypt
  template:
    metadata:
      labels:
        app: encrypt
    spec:
      serviceAccountName: encrypt
      containers:
      - image: rjmp1991/rsaoaep:amd64
        imagePullPolicy: IfNotPresent
        name: encriptcontainer
        ports:
        - containerPort: 80